server:
  port: 8080
spring:
  application:
    name: ktadmin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ktadmin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Zt_199196
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    open-in-view: true
    show-sql: true
    #新版本的jdbc带来的时区问题，如果不加下面的会造成存储到数据库的时间早了13个小时
    properties:
      hibernate:
        jdbc:
          time_zone: Hongkong
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  file:
    path: ./
